language: node_js
sudo: required
services:
    - mongodb
node_js:
    - "5.1.0"
    - "4.2.2"
    - "0.12"
    - "0.10"
before_script:
    - rm -rf ./node_modules
env:
    - CXX=g++-4.8
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.8
            - libkrb5-dev
